name: pr-deployment

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy the pull request
        run: |
          # deployment logic goes here
          sleep 10

          # instead we randomly succeed or fail the deployment
          # exit $(( $RANDOM % 10 >= 5 ))